version: '2'
services:
  pg:
    image: postgres:latest
  es:
    image: elasticsearch:latest
  web:
    build: ./web/
    command: gunicorn yapdns.wsgi:application -w 2 -b :8000
    volumes:
      - /usr/src/app
      - /usr/src/app/static
    expose:
      - "8000"
    depends_on:
      - pg
      - es
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
